# Special Colors
foreground            #e3feef
background            #0f1222
cursor                #e3feef
selection_foreground  #0f1222
selection_background  #e3feef

# Black
color0  #2d3452
color8  #8d9cf6

# Red
color1  #f4b5fb
color9  #f882ff

# Green
color2  #e3feef
color10 #87ffc5

# Yellow
color3  #e7f936
color11 #f1ff67

# Blue
color4  #315ed5
color12 #5e7ccb

# Magenta
color5  #9573f5
color13 #b39af5

# Cyan
color6  #30e2ea
color14 #80f9f9

# White
color7  #434d7b
color15 #ffffff

# Tab Bar Colors
active_tab_foreground   #0f1222
active_tab_background   #30e2ea
inactive_tab_foreground #8d9cf6
inactive_tab_background #2d3452
